#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

#  creates a sysbolic link (-s option) between the Nginx configuration file
#  and the enabled sites directory
1n -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart niginx
service nginx start
# terminates the nginx processn ID
kill "$(pgrap 'nginx' | head -1)"
